# Generated by Django 2.2.5 on 2019-09-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Db',
            new_name='Bb',
        ),
    ]
